# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'KSTestFacebookProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
  # Pods for KSTestFacebookProject

end
